// <auto-generated />
using System;
using System.Collections.Generic;
using AnimeList.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimeList.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805210538_AddMoreTable")]
    partial class AddMoreTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimeFanSub", b =>
                {
                    b.Property<int>("AnimesId")
                        .HasColumnType("integer");

                    b.Property<int>("FanSubsId")
                        .HasColumnType("integer");

                    b.HasKey("AnimesId", "FanSubsId");

                    b.HasIndex("FanSubsId");

                    b.ToTable("AnimeFanSub");
                });

            modelBuilder.Entity("AnimeGenre", b =>
                {
                    b.Property<int>("AnimesId")
                        .HasColumnType("integer");

                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.HasKey("AnimesId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("AnimeGenre");
                });

            modelBuilder.Entity("AnimeList.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int?>("Episodes")
                        .HasColumnType("integer");

                    b.Property<int?>("FanSubId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MalId")
                        .HasColumnType("integer");

                    b.Property<float?>("MalScore")
                        .HasColumnType("real");

                    b.Property<string>("Season")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("TrailerUrls")
                        .HasColumnType("text[]");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Descriptions", "AnimeList.Models.Anime.Descriptions#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.Property<string>("Hu");

                            b1
                                .ToJson("Descriptions")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Titles", "AnimeList.Models.Anime.Titles#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En");

                            b1.Property<string>("JpKanji")
                                .IsRequired();

                            b1.Property<string>("JpRomaji")
                                .IsRequired();

                            b1
                                .ToJson("Titles")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MalId")
                        .IsUnique();

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("AnimeList.Models.FanSub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Links", "AnimeList.Models.FanSub.Links#Link", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Discord");

                            b1.Property<string>("IndaVideo");

                            b1.Property<string>("Videa");

                            b1.Property<string>("WebSite");

                            b1.Property<string>("Youtube");

                            b1
                                .ToJson("Links")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.ToTable("FanSubs");
                });

            modelBuilder.Entity("AnimeList.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("AnimeList.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Studios");
                });

            modelBuilder.Entity("AnimeStudio", b =>
                {
                    b.Property<int>("AnimesId")
                        .HasColumnType("integer");

                    b.Property<int>("StudiosId")
                        .HasColumnType("integer");

                    b.HasKey("AnimesId", "StudiosId");

                    b.HasIndex("StudiosId");

                    b.ToTable("AnimeStudio");
                });

            modelBuilder.Entity("AnimeFanSub", b =>
                {
                    b.HasOne("AnimeList.Models.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeList.Models.FanSub", null)
                        .WithMany()
                        .HasForeignKey("FanSubsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeGenre", b =>
                {
                    b.HasOne("AnimeList.Models.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeList.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeStudio", b =>
                {
                    b.HasOne("AnimeList.Models.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeList.Models.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudiosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
